name: basic compilation test
run-name: ${{ github.actor }} basic compilation test ⚗️
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
    steps:
      - name: add missing packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: uthash-dev
      - name: libyang v2.1.148 from upstream
        uses: actions/checkout@v4
        with:
          repository: 'CESNET/libyang.git'
          ref: 'v2.1.148'
      - name: make libyang v2.1.148 from upstream
        run : mkdir build && cd build && cmake -DCMAKE_LIBRARY_PATH:PATH=$(pwd)/bin -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/bin -DCMAKE_BUILD_TYPE:String="Release" .. && make -j $(nproc) && make install
      - name: sysrepo v2.2.150 from upstream
        uses: actions/checkout@v4
        with:
          repository: 'sysrepo/sysrepo.git'
          ref: 'v2.2.150'
      - name: make sysrepo v2.2.150 from upstream
        run : mkdir build && cd build && cmake -DLIBYANG_LIBRARY:PATH=$(pwd)/bin -DLIBYANG_INCLUDE_DIR:PATH=$(pwd)/bin -DCMAKE_LIBRARY_PATH:PATH=$(pwd)/bin -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/bin -DCMAKE_BUILD_TYPE:String="Release" .. && make -j $(nproc) && make install
      - name: check sysrepo running ok
        run : sysrepoctl -l
      - name: checkout
        uses: actions/checkout@v4
      - name: make
        run : CC=${{ matrix.compiler }} make -j $(nproc)
      - name: basic check
        run : ldd onmcli
